// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import (
	"fmt"
)

func fib(n int) (s int) {
	// s is the sum of the even-valued terms
	s = 0
	for first, second := 0, 1; first < n; first, second = second, first+second {
		if first%2 == 0 {
			s += first
		}
	}
	return
}

func main() {
	fmt.Println(fib(4000000))
}
